using Tyuiu.EvdokimovKP.Sprint5.Task6.V2.Lib;
using System.IO;
DataService ds = new DataService();
Console.WriteLine("********************************************************************");
Console.WriteLine("ИСХОДНЫЕ ДАННЫЕ:                                                    ");
Console.WriteLine("********************************************************************");
string path = Path.Combine(Path.GetTempPath(), "InPutDataFileTask6V2.txt");
Console.WriteLine("Данные взяты из файла: " + path);
Console.WriteLine();
Console.WriteLine("Данные из файла: ");
Console.WriteLine(File.ReadAllText(path));
Console.WriteLine("********************************************************************");
Console.WriteLine("РЕЗУЛЬТАТ:                                                          ");
Console.WriteLine("********************************************************************");
double res = ds.LoadFromDataFile(path);
Console.WriteLine("Файл: " + path);
Console.WriteLine("Ответ: " + res);
Console.WriteLine("Создан!");
Console.ReadKey();