using Tyuiu.EvdokimovKP.Sprint5.Task0.V27.Lib;
DataService ds = new DataService();
Console.WriteLine("********************************************************************");
Console.WriteLine("ИСХОДНЫЕ ДАННЫЕ:                                                    ");
Console.WriteLine("********************************************************************");
int x = 3;
Console.WriteLine("x = " + x);
Console.WriteLine("********************************************************************");
Console.WriteLine("РЕЗУЛЬТАТ:                                                          ");
Console.WriteLine("********************************************************************");
string res = ds.SaveToFileTextData(x);
Console.WriteLine("Файл: " + res);
Console.WriteLine("Создан!");
Console.ReadKey();